# Устанавливаем .env по умолчанию
ENV_FILE ?= .env

# Команды

up:
	@echo "📦 Запуск docker-compose..."
	docker compose --env-file $(ENV_FILE) up --build

down:
	@echo "🛑 Остановка контейнеров..."
	docker compose down

logs:
	@echo "📋 Логи всех контейнеров:"
	docker compose logs -f

restart:
	@echo "🔄 Перезапуск контейнеров..."
	docker compose down && docker compose --env-file $(ENV_FILE) up --build

shell:
	@echo "💻 Вход в flask-app shell..."
	docker exec -it flask-app bash

ps:
	docker compose ps

prune:
	@echo "🧹 Удаление неиспользуемых томов, сетей и образов..."
	docker system prune -f

# Только база
db-shell:
	docker exec -it postgres psql -U postgres -d mydb
