apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: {{ .Values.flaskApp.image }}
          ports:
            - containerPort: {{ .Values.flaskApp.port }}
          env:
            - name: REDIS_HOST
              value: "redis"
